In [1]:
%load_ext autoreload
%autoreload 2

import datetime as dt
import os
from typing import Dict

import pandas as pd

import helpers.s3 as hs3
import vendors2.kibot.data.load as kdl
import vendors2.kibot.data.load.file_path_generator as fpgen
import vendors2.kibot.data.types as types

In [2]:
file = "s3://external-p1/kibot/pq/all_stocks_1min/AAPL.pq"

pd.read_parquet(file)

                       open    high     low   close   vol
datetime
2015-09-29 04:00:00  103.90  103.96  103.90  103.96   974
2015-09-29 04:07:00  104.24  104.24  104.24  104.24   108
2015-09-29 04:13:00  104.29  104.29  104.29  104.29   216
2015-09-29 04:14:00  104.34  104.36  104.34  104.34  2272
2015-09-29 04:18:00  104.37  104.37  104.37  104.37   962
...                     ...     ...     ...     ...   ...
2020-08-18 16:08:00  462.17  462.19  462.17  462.19  1006
2020-08-18 16:09:00  462.18  462.19  462.18  462.18   509
2020-08-18 16:10:00  462.18  462.18  462.11  462.11  2874
2020-08-18 16:11:00  462.10  462.10  462.10  462.10  1475
2020-08-18 16:12:00  462.11  462.14  462.11  462.14   722

[794492 rows x 5 columns]